version: '3.4'

services:
 catalogdb:
    image: mongo
 basketdb:
    image: redis:7.0.0-alpine
    container_name: redis
  

 catalog.api:
   image: ${DOCKER_REGISTRY-}catalogapi
   build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

 basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

volumes:
   mongo_data:

